server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka #注册中心单机版
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/ #注册中心集群版
  instance:
    instance-id: order80
    prefer-ip-address: true

